import { company } from "./site-data";

export const competitorInsights = [
  {
    name: "OpenSolar",
    focus: "Free design, proposals, CRM, roles, payments and API connectors.",
    lesson: "Bundle proposal and CRM flows so small installers avoid duplicate data entry.",
  },
  {
    name: "Aurora Solar",
    focus: "Premium 3D design, shade analysis and bankable production reports.",
    lesson: "Keep technical site-survey and generation assumptions attached to each deal.",
  },
  {
    name: "Enerflo",
    focus: "Lead-to-PTO workflow with lender, portal and integration depth.",
    lesson: "Make every stage visible from sales through installation approval.",
  },
  {
    name: "Coperniq",
    focus: "Build, monitor and dispatch OS for solar operations.",
    lesson: "Add stage blockers, work orders and service tickets for operational control.",
  },
  {
    name: "Payaca",
    focus: "Solar CRM, quoting, field app, customer portal and permit tracking.",
    lesson: "Give customers status visibility and reduce admin calls.",
  },
];

export const saasModules = [
  "Lead CRM with stage pipeline",
  "Solar savings calculator capture",
  "Proposal and quote workspace",
  "Site survey checklist",
  "Permit and document tracker",
  "Crew dispatch and work orders",
  "Inventory and asset register",
  "Customer portal milestones",
  "Monitoring tickets and O&M",
  "Analytics, conversion and revenue dashboard",
];

export const dashboardSeed = {
  metrics: [
    { label: "Pipeline Value", value: "Rs. 42.8L", delta: "+18%" },
    { label: "Active Leads", value: "36", delta: "+9" },
    { label: "Projects in Install", value: "8", delta: "+3" },
    { label: "Service Tickets", value: "5", delta: "-2" },
  ],
  pipeline: [
    { stage: "New", count: 12, value: "Rs. 8.4L" },
    { stage: "Survey", count: 9, value: "Rs. 10.2L" },
    { stage: "Proposal", count: 7, value: "Rs. 12.7L" },
    { stage: "Won", count: 4, value: "Rs. 6.9L" },
    { stage: "Install", count: 4, value: "Rs. 4.6L" },
  ],
  leads: [
    {
      name: "Rahul Patil",
      phone: "9272112004",
      email: "rahul.patil@example.com",
      pincode: "416416",
      city: "Sangli",
      type: "home",
      monthlyBill: "Rs. 4,000 - Rs. 10,000",
      source: "Website calculator",
      stage: "survey",
      priority: "High",
      roofType: "RCC terrace",
      estimatedSystemSizeKw: 5.2,
      expectedValue: 325000,
      notes: "Interested in subsidy and EMI plan. Asked for weekend rooftop survey near Sangalwadi.",
      createdAt: "2026-05-27T10:30:00.000Z",
      updatedAt: "2026-05-29T14:10:00.000Z",
    },
    {
      name: "Sangli Foods Pvt Ltd",
      phone: "9822012345",
      email: "operations@sanglifoods.example",
      pincode: "416416",
      city: "Sangli",
      type: "commercial",
      monthlyBill: "Above Rs. 2 Lacs",
      source: "Facebook",
      stage: "proposal",
      priority: "Critical",
      roofType: "Metal sheet roof",
      estimatedSystemSizeKw: 82,
      expectedValue: 4100000,
      notes: "Factory wants daytime captive consumption study and accelerated depreciation explanation.",
      createdAt: "2026-05-22T09:00:00.000Z",
      updatedAt: "2026-05-30T11:45:00.000Z",
    },
    {
      name: "Green Park CHS",
      phone: "9766601122",
      email: "committee@greenpark.example",
      pincode: "416410",
      city: "Miraj",
      type: "society",
      monthlyBill: "Rs. 50,000 - Rs. 2 Lacs",
      source: "Referral",
      stage: "qualified",
      priority: "Medium",
      roofType: "Common terrace",
      estimatedSystemSizeKw: 18,
      expectedValue: 990000,
      notes: "Committee needs AGM presentation, subsidy note, and common-area savings estimate.",
      createdAt: "2026-05-18T12:20:00.000Z",
      updatedAt: "2026-05-21T16:05:00.000Z",
    },
  ],
  projects: [
    {
      customerName: "Sangli Textile Works",
      systemSizeKw: 38,
      city: "Sangli",
      status: "permit",
      value: 1780000,
      nextAction: "Upload DISCOM approval documents",
      assignedTo: "Operations",
      customerType: "Commercial",
      permitStatus: "Awaiting DISCOM approval",
      paymentStatus: "Advance received",
      siteAddress: "MIDC Kupwad, Sangli",
      surveySummary: "Shadow-free metal sheet roof with good daytime load matching.",
      documents: "Load bill, site photos, roof measurement, SLD draft",
      timeline: "Target installation within 18 days after approval.",
    },
    {
      customerName: "Sangalwadi Residency",
      systemSizeKw: 22,
      city: "Sangalwadi",
      status: "install",
      value: 1160000,
      nextAction: "Schedule ACDB and inverter commissioning",
      assignedTo: "Field Crew",
      customerType: "Housing Society",
      permitStatus: "Approved",
      paymentStatus: "Second milestone pending",
      siteAddress: "Sangalwadi, Sangli 416416",
      surveySummary: "Common-area load with water pump and lighting usage. Installation split across two terraces.",
      documents: "AGM approval, subsidy note, structural photos, material checklist",
      timeline: "Commissioning planned this week.",
    },
    {
      customerName: "Miraj Clinic",
      systemSizeKw: 12,
      city: "Miraj",
      status: "survey",
      value: 640000,
      nextAction: "Complete rooftop shade photos",
      assignedTo: "Survey Team",
      customerType: "Commercial",
      permitStatus: "Not started",
      paymentStatus: "Quotation pending",
      siteAddress: "Miraj main road",
      surveySummary: "Partial shadow from adjacent structure. Need final panel layout before proposal.",
      documents: "Electricity bill received. Roof photos pending.",
      timeline: "Proposal due after survey completion.",
    },
  ],
  content: {
    heroTitle: `${company.name} brings solar home.`,
    heroSubtitle: company.description,
    primaryCta: "Schedule a FREE Visit",
    phone: company.phone,
    email: company.email,
    address: company.address,
  },
};
